package sign

import (
	"bytes"
	"crypto/ed25519"
	"encoding/json"
	"time"
)

type vectorKey struct {
	Seed      string `json:"seed"`
	PublicKey string `json:"publicKey"`
	KeyID     string `json:"keyId"`
}

type certCase struct {
	Name        string      `json:"name"`
	Certificate Certificate `json:"certificate"`
	Root        string      `json:"root"`
	Use         string      `json:"use"`
	Now         string      `json:"now"`
	Valid       bool        `json:"valid"`
}

type messageCase struct {
	Name    string         `json:"name"`
	Message string         `json:"message"`
	Signed  SignedManifest `json:"signed"`
	Root    string         `json:"root"`
	Now     string         `json:"now"`
	Valid   bool           `json:"valid"`
}

type vectors struct {
	Comment []string          `json:"_comment"`
	Domains map[string]string `json:"domains"`
	KeyID   struct {
		PublicKey string `json:"publicKey"`
		KeyID     string `json:"keyId"`
	} `json:"keyIdVector"`
	Roots            map[string]vectorKey   `json:"roots"`
	Subjects         map[string]vectorKey   `json:"subjects"`
	Certificates     map[string]Certificate `json:"certificates"`
	CertificateCases []certCase             `json:"certificateCases"`
	MessageCases     []messageCase          `json:"messageCases"`
}

func vk(k ed25519.PrivateKey) vectorKey {
	p := k.Public().(ed25519.PublicKey)
	return vectorKey{Seed: b64.EncodeToString(k.Seed()), PublicKey: b64.EncodeToString(p), KeyID: KeyID(p)}
}

func generateVectors() ([]byte, error) {
	rootKey, otherRoot := seedKey(0x11), seedKey(0x22)
	nb := time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)
	inWindow := nb.AddDate(0, 0, 30).Format(time.RFC3339)

	v := vectors{
		Comment: []string{
			"Cross-repo contract: ClaudiniteEngine (Go, shared/sign) and the ClaudiniteLicenses Worker (JavaScript) must both pass every case here.",
			"Generated by shared/sign/vectors_gen_test.go; regenerate with: go test ./shared/sign -run TestVectorsFileIsCurrent -update",
			"Encoding: b64 means base64url without padding. Times are RFC 3339 UTC.",
			"Certificate: payload = b64(body JSON); signature = b64(Ed25519(domains.certificate || decoded payload bytes)) by the issuing root.",
			"Verify a certificate: issuer is the key id of a trusted root and the signature verifies; v is 1; use equals the use asked for; keyId equals the key id of publicKey; notAfter - notBefore is at most 400 days; notBefore <= now <= notAfter.",
			"Key id: first 16 hex chars of SHA-256 over the raw 32-byte public key.",
			"Signed manifest: signature = b64(Ed25519(domains.manifest || SHA-512(manifest bytes))) by the certificate's subject key; the certificate must verify for use manifest.",
			"Seeds here are test keys only and sign nothing anyone trusts.",
		},
		Domains:      map[string]string{"certificate": CertDomain, "manifest": ManifestDomain},
		Roots:        map[string]vectorKey{"root": vk(rootKey), "other": vk(otherRoot)},
		Subjects:     map[string]vectorKey{},
		Certificates: map[string]Certificate{},
	}
	rp := rootKey.Public().(ed25519.PublicKey)
	v.KeyID.PublicKey, v.KeyID.KeyID = b64.EncodeToString(rp), KeyID(rp)

	uses := []Use{UseManifest, UsePacks, UseLicense, UseLicensePublic}
	subjects := map[Use]ed25519.PrivateKey{}
	for i, u := range uses {
		s := seedKey(byte(0x31 + i))
		subjects[u] = s
		v.Subjects[string(u)] = vk(s)
		c, err := Issue(rootKey, s.Public().(ed25519.PublicKey), u, nb, nb.AddDate(0, 0, 90))
		if err != nil {
			return nil, err
		}
		v.Certificates[string(u)] = c
		v.CertificateCases = append(v.CertificateCases, certCase{"valid " + string(u), c, "root", string(u), inWindow, true})
	}
	m := v.Certificates[string(UseManifest)]
	l := v.Certificates[string(UseLicense)]
	mutated := func(c Certificate, payload bool) Certificate {
		if payload {
			c.Payload = flip(c.Payload, 30)
		} else {
			c.Signature = flip(c.Signature, 10)
		}
		return c
	}
	long := issueUnchecked(rootKey, subjects[UseManifest].Public().(ed25519.PublicKey), UseManifest, nb, nb.AddDate(0, 0, 401))
	v.CertificateCases = append(v.CertificateCases,
		certCase{"manifest certificate asked for license", m, "root", "license", inWindow, false},
		certCase{"license certificate asked for manifest", l, "root", "manifest", inWindow, false},
		certCase{"verified against another root", m, "other", "manifest", inWindow, false},
		certCase{"not yet valid", m, "root", "manifest", nb.Add(-time.Second).Format(time.RFC3339), false},
		certCase{"expired", m, "root", "manifest", nb.AddDate(0, 0, 90).Add(time.Second).Format(time.RFC3339), false},
		certCase{"validity over 400 days", long, "root", "manifest", inWindow, false},
		certCase{"flipped payload byte", mutated(m, true), "root", "manifest", inWindow, false},
		certCase{"flipped signature byte", mutated(m, false), "root", "manifest", inWindow, false},
		certCase{"unknown use asked", m, "root", "release", inWindow, false},
	)

	msg := []byte(`{"v":1,"version":"1.1.0"}` + "\n")
	signed := SignManifest(subjects[UseManifest], m, msg)
	badMsg := append([]byte{}, msg...)
	badMsg[5] ^= 1
	badSig := signed
	badSig.Signature = flip(signed.Signature, 7)
	badCert := signed
	badCert.Certificate = mutated(m, true)
	v.MessageCases = []messageCase{
		{"valid signed manifest", b64.EncodeToString(msg), signed, "root", inWindow, true},
		{"flipped message byte", b64.EncodeToString(badMsg), signed, "root", inWindow, false},
		{"flipped signature byte", b64.EncodeToString(msg), badSig, "root", inWindow, false},
		{"flipped certificate payload byte", b64.EncodeToString(msg), badCert, "root", inWindow, false},
		{"signed by a license-use key", b64.EncodeToString(msg), SignManifest(subjects[UseLicense], l, msg), "root", inWindow, false},
	}
	var out bytes.Buffer
	enc := json.NewEncoder(&out)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(v); err != nil {
		return nil, err
	}
	return out.Bytes(), nil
}
