package packset

import (
	"bytes"
	"io/fs"
	"os"
	"path/filepath"
	"sort"

	"github.com/missingbulb/ClaudiniteEngine/cn/shared/settings"
)

// Engine is a pack the binary carries: written under TempDir/<id> each
// time the set is loaded, where the settings turn it on, and loaded like
// a canon pack from there. The folder is never tracked, so a member holds
// no copy an update would have to move.
const Engine Kind = "engine"

// Embedded is one pack the engine carries.
type Embedded struct {
	ID    string
	Files fs.FS
	// Active says whether the repo's settings turn the pack on.
	Active func(settings.Parsed) bool
}

var embedded []Embedded

// RegisterEmbedded adds a pack the binary carries; the package holding
// its files registers it from init.
func RegisterEmbedded(e Embedded) { embedded = append(embedded, e) }

// tempIgnore keeps the whole temp root out of git; a file another step
// wrote there is left as it is.
const tempIgnore = "# GENERATED by cn: written for each run from the engine. Not tracked.\n*\n"

// materialize makes TempDir/<id> hold exactly e's files: a file that
// already reads the same is not rewritten, and one e no longer carries is
// removed.
func materialize(repo string, e Embedded) error {
	dir := filepath.Join(repo, filepath.FromSlash(TempDir), e.ID)
	ignore := filepath.Join(repo, filepath.FromSlash(TempDir), "..", ".gitignore")
	if _, err := os.Stat(ignore); err != nil {
		if err := os.MkdirAll(filepath.Dir(ignore), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(ignore, []byte(tempIgnore), 0o644); err != nil {
			return err
		}
	}
	want := map[string]bool{}
	err := fs.WalkDir(e.Files, ".", func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		raw, err := fs.ReadFile(e.Files, p)
		if err != nil {
			return err
		}
		dest := filepath.Join(dir, filepath.FromSlash(p))
		want[dest] = true
		if have, err := os.ReadFile(dest); err == nil && bytes.Equal(have, raw) {
			return nil
		}
		if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
			return err
		}
		return os.WriteFile(dest, raw, 0o644)
	})
	if err != nil {
		return err
	}
	var stale []string
	_ = filepath.WalkDir(dir, func(p string, d fs.DirEntry, err error) error {
		if err == nil && !d.IsDir() && !want[p] {
			stale = append(stale, p)
		}
		return nil
	})
	sort.Strings(stale)
	for _, p := range stale {
		if err := os.Remove(p); err != nil {
			return err
		}
	}
	return nil
}

// activeEmbedded are the registered packs the settings turn on, by id.
func activeEmbedded(parsed settings.Parsed) []Embedded {
	var out []Embedded
	for _, e := range embedded {
		if e.Active(parsed) {
			out = append(out, e)
		}
	}
	sort.Slice(out, func(i, k int) bool { return out[i].ID < out[k].ID })
	return out
}
