// Package userpack copies the pack belonging to the person in front of a
// session out of their store repository into the repo's session pack
// root, .claudinite/temp/packs/current_user/, where the pack loader finds
// it beside the declared packs. It runs as a SessionStart step wherever
// claude-code-web-users-support is declared, before the session's pack
// set is read, so the person's rules reach the rules index's import and
// their skills are mounted with the rest.
//
// The store's address is the pack entry's config: repo (owner/name,
// required) and path (default preferences), one directory per person
// named for their GitHub login in lower case. The login is what GET /user
// answers for the session's GH_TOKEN, then GITHUB_TOKEN.
//
// Fail-soft throughout: no store, an unattended session, no login, no
// directory for this person, a clone that fails or a pack past the budget
// each leave the placeholder prose, and the step's one line says which.
// What it writes is Markdown, JavaScript modules and JSON under one
// directory, within a file count and byte budget. The store is as trusted
// as the repo, since a pack is what a session runs; no cap here replaces
// that.
package userpack

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/missingbulb/ClaudiniteEngine/cn/helpers/proc"
	"github.com/missingbulb/ClaudiniteEngine/cn/packaging/packset"
	"github.com/missingbulb/ClaudiniteEngine/cn/packaging/settings"
)

// Pack is the declaration that turns the step on.
const Pack = packset.UserPackID

// DefaultPath is where the people sit in the store when the config names
// no path.
const DefaultPath = "preferences"

// PackDir is where the copy lands, repo-relative.
const PackDir = packset.TempDir + "/" + packset.CurrentUser

// LoginRecord is the login the step read, or why it read none.
const LoginRecord = ".claudinite/temp/current_user_login.json"

// Placeholder is the prose a session gets when no pack was copied: the
// rules index imports the path literally, so a file is always there.
const Placeholder = "<!-- No personal pack was copied into this session. -->\n"

const sessionRootIgnore = "# GENERATED by claude-code-web-users-support: session state, copied in every session\n# start. Not tracked.\n*\n"

const synthesizedManifest = `{
  "ruleRoutingGuidance": {
    "belongs": "how this person wants to be worked with, in every project they work in",
    "excludes": "a project's own conventions, which belong to the packs that own each subject"
  }
}
`

// The budget a person's pack is copied within.
const (
	MaxFiles     = 60
	MaxBytes     = 512 * 1024
	cloneTimeout = 60 * time.Second
	loginTimeout = 10 * time.Second
)

var (
	copyable  = regexp.MustCompile(`\.(md|mjs|json)$`)
	storeRepo = regexp.MustCompile(`^[^/\s]+/[^/\s]+$`)
	pathTrim  = regexp.MustCompile(`^\./+|/+$`)
)

// Store is a resolved store address.
type Store struct{ Repo, Path string }

// ResolveStore is the store a config names, nil where it names none or
// one that cannot be used.
func ResolveStore(config map[string]any) *Store {
	repo, ok := config["repo"].(string)
	if !ok || !storeRepo.MatchString(repo) {
		return nil
	}
	p := DefaultPath
	if v, set := config["path"]; set {
		s, ok := v.(string)
		if !ok || strings.Contains(s, "..") || strings.HasPrefix(s, "/") {
			return nil
		}
		p = s
	}
	if p = pathTrim.ReplaceAllString(p, ""); p == "" {
		p = DefaultPath
	}
	return &Store{Repo: repo, Path: p}
}

// Dir is one person's directory in the store.
func (s Store) Dir(login string) string { return s.Path + "/" + login }

// UsableIdentity reports whether name is a GitHub login in lower case: it
// becomes a path segment and an argument to git, so it is held to
// GitHub's own rule.
func UsableIdentity(name string) bool {
	if len(name) == 0 || len(name) > 39 {
		return false
	}
	for i := 0; i < len(name); i++ {
		c := name[i]
		alnum := c >= 'a' && c <= 'z' || c >= '0' && c <= '9'
		if alnum {
			continue
		}
		if c != '-' || i == 0 || i == len(name)-1 || name[i+1] == '-' {
			return false
		}
	}
	return true
}

// DeclineReason is why this session gets no personal pack, "" when it
// should get one: no usable store, or a session declared unattended.
func DeclineReason(config map[string]any, getenv func(string) string) string {
	if ResolveStore(config) == nil {
		return `this project declares no store for personal packs (the pack entry's "config": { "repo": … })`
	}
	if getenv("CLAUDE_CODE_SESSION_ATTENDED") == "0" {
		return "the session is unattended (CLAUDE_CODE_SESSION_ATTENDED=0) and a personal pack is for a present person"
	}
	return ""
}

// Identity is the login the session carries, or why none was read.
type Identity struct {
	Login string `json:"login,omitempty"`
	Via   string `json:"via,omitempty"`
	Error string `json:"error,omitempty"`
}

// ReadLogin asks GitHub who the session's token belongs to, GH_TOKEN
// then GITHUB_TOKEN; CLAUDINITE_GITHUB_USER_URL replaces the endpoint.
func ReadLogin(getenv func(string) string, client *http.Client) Identity {
	url := getenv("CLAUDINITE_GITHUB_USER_URL")
	if url == "" {
		url = "https://api.github.com/user"
	}
	var held []string
	for _, n := range []string{"GH_TOKEN", "GITHUB_TOKEN"} {
		if getenv(n) != "" {
			held = append(held, n)
		}
	}
	if len(held) == 0 {
		return Identity{Error: "neither GH_TOKEN nor GITHUB_TOKEN is set"}
	}
	var misses []string
	for _, name := range held {
		login, isString, err := userLogin(client, url, getenv(name))
		if err != nil {
			misses = append(misses, name+": "+err.Error())
			continue
		}
		if !isString || !UsableIdentity(strings.ToLower(login)) {
			return Identity{Error: fmt.Sprintf("%s read back %q, which is not a usable GitHub login", name, login)}
		}
		return Identity{Login: login, Via: name}
	}
	return Identity{Error: "GET /user answered no login (" + strings.Join(misses, "; ") + ")"}
}

// userLogin is the answer's login as text, and whether it was a JSON string.
func userLogin(client *http.Client, url, token string) (string, bool, error) {
	ctx, cancel := context.WithTimeout(context.Background(), loginTimeout)
	defer cancel()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return "", false, err
	}
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("User-Agent", "claudinite")
	res, err := client.Do(req)
	if err != nil {
		if errors.Is(err, context.DeadlineExceeded) {
			return "", false, errors.New("timed out")
		}
		return "", false, errors.New("unreachable")
	}
	defer func() { _ = res.Body.Close() }()
	if res.StatusCode/100 != 2 {
		return "", false, fmt.Errorf("HTTP %d", res.StatusCode)
	}
	var body struct {
		Login json.RawMessage `json:"login"`
	}
	if err := json.NewDecoder(io.LimitReader(res.Body, 1<<20)).Decode(&body); err != nil {
		return "", false, errors.New("the answer is not JSON")
	}
	if len(body.Login) == 0 {
		return "undefined", false, nil
	}
	var s string
	if string(body.Login) != "null" && json.Unmarshal(body.Login, &s) == nil {
		return s, true, nil
	}
	return string(body.Login), false, nil
}

// Result is what the step did, for its one line.
type Result struct {
	// Declined is why the session gets no pack; Identity the login read.
	Declined string
	Identity Identity
	Store    *Store
	// Copied is true when the person's pack landed; Err is a clone or
	// copy failure, which still leaves the placeholder.
	Copied bool
	Err    error
}

// Line is the step's one sentence for the session.
func (r Result) Line() string {
	const tail = " - proceeding with default interaction behavior."
	switch {
	case r.Declined != "":
		return "[cn] personal pack: " + r.Declined + tail
	case r.Identity.Login == "":
		why := r.Identity.Error
		if why == "" {
			why = "nothing recorded"
		}
		return "[cn] personal pack: no GitHub login was read for this session (" + why + ")" + tail
	}
	dir := r.Store.Dir(strings.ToLower(r.Identity.Login)) + "/"
	if r.Copied {
		return fmt.Sprintf("[cn] personal pack: copied %s from %s for GitHub user %s.", dir, r.Store.Repo, r.Identity.Login)
	}
	why := ""
	if r.Err != nil {
		why = " (" + r.Err.Error() + ")"
	}
	return fmt.Sprintf("[cn] personal pack: %s holds no pack at %s for GitHub user %s, or it could not be read%s%s", r.Store.Repo, dir, r.Identity.Login, why, tail)
}

// Env is what the step reads of the process.
type Env struct {
	Getenv func(string) string
	Client *http.Client
}

// Declared is the pack entry's config and whether the repo declares the
// pack at all; a repo whose settings do not read declares nothing.
func Declared(repo string) (map[string]any, bool) {
	p, f, err := settings.Find(repo)
	if err != nil {
		return nil, false
	}
	raw, err := os.ReadFile(p)
	if err != nil {
		return nil, false
	}
	packs, err := settings.ReadPacks(raw, f)
	if err != nil {
		return nil, false
	}
	e, ok := packs.Entry(Pack, false)
	return e.Config, ok
}

// Prepare is the SessionStart step: where the pack is declared, the
// person's pack copied in, or the placeholder; ok is false where the pack
// is not declared and nothing was touched.
func Prepare(repo string, env Env) (Result, bool) {
	config, ok := Declared(repo)
	if !ok {
		return Result{}, false
	}
	r := Result{Store: ResolveStore(config), Declined: DeclineReason(config, env.Getenv)}
	if r.Declined == "" {
		r.Identity = ReadLogin(env.Getenv, env.Client)
	}
	if raw, err := json.Marshal(r.Identity); err == nil {
		_ = writeFile(filepath.Join(repo, filepath.FromSlash(LoginRecord)), append(raw, '\n'))
	}
	r.Copied, r.Err = Copy(repo, r.Store, r.Declined, r.Identity.Login, env.Getenv)
	return r, true
}

func writeFile(p string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		return err
	}
	return os.WriteFile(p, data, 0o644)
}

// leavePlaceholder writes the placeholder where dest holds no rules, and
// otherwise leaves an earlier session's copy standing, as the Node step did.
func leavePlaceholder(dest string) {
	if _, err := os.Stat(filepath.Join(dest, "RULES.md")); err == nil {
		return
	}
	_ = writeFile(filepath.Join(dest, "RULES.md"), []byte(Placeholder))
}

// Copy copies login's pack from the store into repo's session pack root:
// the working tree's own directory first, where the repo is the store and
// its owner is editing it, else a shallow sparse clone. Any miss leaves
// the placeholder; copied is true only when the pack landed.
func Copy(repo string, store *Store, declined, login string, getenv func(string) string) (copied bool, err error) {
	dest := filepath.Join(repo, filepath.FromSlash(PackDir))
	_ = writeFile(filepath.Join(repo, ".claudinite", "temp", ".gitignore"), []byte(sessionRootIgnore))
	if declined != "" || login == "" || store == nil {
		leavePlaceholder(dest)
		return false, nil
	}
	dir := store.Dir(strings.ToLower(login))
	source := filepath.Join(repo, filepath.FromSlash(dir))
	if _, serr := os.Stat(source); serr != nil {
		clone, cerr := checkout(store, dir, getenv)
		if clone != "" {
			defer func() { _ = os.RemoveAll(clone) }()
		}
		if cerr != nil {
			leavePlaceholder(dest)
			return false, cerr
		}
		source = filepath.Join(clone, filepath.FromSlash(dir))
	}
	if st, serr := os.Stat(source); serr != nil || !st.IsDir() {
		leavePlaceholder(dest)
		return false, nil
	}
	wanted := treeFiles(source)
	if len(wanted) == 0 || len(wanted) > MaxFiles {
		leavePlaceholder(dest)
		return false, nil
	}
	if err := os.RemoveAll(dest); err != nil {
		leavePlaceholder(dest)
		return false, err
	}
	bytes := 0
	manifest := false
	for _, rel := range wanted {
		data, rerr := os.ReadFile(filepath.Join(source, filepath.FromSlash(rel)))
		if rerr != nil {
			continue
		}
		if bytes += len(data); bytes > MaxBytes {
			_ = os.RemoveAll(dest)
			leavePlaceholder(dest)
			return false, nil
		}
		if werr := writeFile(filepath.Join(dest, filepath.FromSlash(rel)), data); werr != nil {
			_ = os.RemoveAll(dest)
			leavePlaceholder(dest)
			return false, werr
		}
		manifest = manifest || rel == "pack.json" || rel == "pack.mjs"
	}
	if !manifest {
		_ = writeFile(filepath.Join(dest, "pack.json"), []byte(synthesizedManifest))
	}
	if _, err := os.Stat(filepath.Join(dest, "RULES.md")); err != nil {
		_ = writeFile(filepath.Join(dest, "RULES.md"), []byte(Placeholder))
	}
	return true, nil
}

// treeFiles are the copyable files under dir, slash-separated and
// sorted; a .git folder and anything not a regular file are skipped.
func treeFiles(dir string) []string {
	var out []string
	_ = filepath.WalkDir(dir, func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() && d.Name() == ".git" {
			return filepath.SkipDir
		}
		if !d.Type().IsRegular() {
			return nil
		}
		rel, rerr := filepath.Rel(dir, p)
		if rerr != nil {
			return nil
		}
		rel = filepath.ToSlash(rel)
		if copyable.MatchString(rel) && path.Clean(rel) == rel && !strings.HasPrefix(rel, "../") {
			out = append(out, rel)
		}
		return nil
	})
	sort.Strings(out)
	return out
}

// checkout is the store's default branch with only dir checked out, in a
// directory the caller removes: a clone, since a private store is
// reachable only through the credentials git already carries. A sparse
// checkout fetches the files it checks out in one batch, where checking a
// path out of a blobless clone fetches each file on its own.
// CLAUDINITE_USER_PACKS_CLONE_URL replaces the address.
func checkout(store *Store, dir string, getenv func(string) string) (string, error) {
	clone, err := os.MkdirTemp("", "claudinite-personal-pack-")
	if err != nil {
		return "", err
	}
	url := getenv("CLAUDINITE_USER_PACKS_CLONE_URL")
	if url == "" {
		url = "https://github.com/" + store.Repo
	}
	if err := git("", "clone", "--quiet", "--depth", "1", "--filter=blob:none", "--sparse", url, clone); err != nil {
		return clone, err
	}
	return clone, git(clone, "sparse-checkout", "set", "--no-cone", dir)
}

func git(dir string, args ...string) error {
	ctx, cancel := context.WithTimeout(context.Background(), cloneTimeout)
	defer cancel()
	cmd := proc.CommandContext(ctx, "git", append([]string{"-c", "maintenance.auto=false", "-c", "gc.auto=0"}, args...)...)
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GIT_TERMINAL_PROMPT=0")
	out, err := cmd.CombinedOutput()
	if ctx.Err() == context.DeadlineExceeded {
		return fmt.Errorf("git %s did not finish in %ds", args[0], int(cloneTimeout.Seconds()))
	}
	if err != nil {
		lines := strings.Split(strings.TrimSpace(string(out)), "\n")
		why := lines[len(lines)-1]
		for _, l := range lines {
			if strings.HasPrefix(l, "fatal: ") {
				why = strings.TrimPrefix(l, "fatal: ")
				break
			}
		}
		return fmt.Errorf("git %s: %s", args[0], why)
	}
	return nil
}
